import {
  Component,
  input,
  output,
  inject,
  signal,
  computed,
  ChangeDetectionStrategy,
  OnInit,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { firstValueFrom } from 'rxjs';
import { deleteField } from '@angular/fire/firestore';
import { ProjectService } from '../../../core/services/project.service';
import { DialogService } from '../../../core/services/dialog.service';
import { AuthService } from '../../../core/auth/auth.service';
import {
  GoogleSheetsService,
  SpreadsheetMetadata,
  SheetTab,
} from '../../../core/services/google-sheets.service';
import {
  GoogleSheetsSyncService,
  DEFAULT_SHEET_TAB_NAME,
} from '../../../core/services/google-sheets-sync.service';
import { GoogleSheetsAutoSyncService } from '../../../core/services/google-sheets-auto-sync.service';
import { Project } from '../../../core/models/domain.model';

/**
 * UI for linking a project to a designated Google Sheet and running
 * on-demand sync. Mirrors ProjectGoogleTasksSyncComponent in behavior.
 */
@Component({
  selector: 'app-project-google-sheets-sync',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './project-google-sheets-sync.component.html',
  styleUrls: ['./project-google-sheets-sync.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProjectGoogleSheetsSyncComponent implements OnInit {
  private readonly projectService = inject(ProjectService);
  private readonly dialogService = inject(DialogService);
  private readonly sheetsService = inject(GoogleSheetsService);
  private readonly sheetsSyncService = inject(GoogleSheetsSyncService);
  private readonly autoSync = inject(GoogleSheetsAutoSyncService);
  private readonly authService = inject(AuthService);

  // Expose auto-sync state to the template so the UI reflects background activity.
  autoSyncing = this.autoSync.syncing;
  autoSyncLastAt = this.autoSync.lastSyncAt;
  autoSyncError = this.autoSync.lastError;

  project = input.required<Project>();
  projectChanged = output<void>();

  isAuthenticated = computed(() => this.sheetsService.isAuthenticated());

  // Linked sheet metadata (fetched after the user pastes an ID or creates a new sheet).
  sheetMetadata = signal<SpreadsheetMetadata | null>(null);
  loadingMetadata = signal(false);

  // Form state for pasting a URL/ID.
  sheetUrlInput = signal('');
  linking = signal(false);

  // Form state for creating a new sheet.
  showCreateForm = signal(false);
  newSheetTitle = signal('');
  newTabName = signal(DEFAULT_SHEET_TAB_NAME);

  // Collapsible "Expected sheet format" help panel.
  showFormatHelp = signal(false);

  // Sync activity state.
  syncing = signal(false);
  pushing = signal(false);
  creating = signal(false);
  lastSyncResult = signal<{ success: boolean; message: string } | null>(null);

  // Column reference shown in the "Expected sheet format" help panel.
  // Keep in sync with SHEET_HEADERS in google-sheets-sync.service.ts.
  readonly expectedColumns: Array<{ name: string; detail: string }> = [
    { name: 'Title', detail: 'Task title. Required — rows without a title are skipped.' },
    {
      name: 'Section',
      detail:
        'Human-readable section name (e.g. "To Do"). Edit this to move the task. Defaults to the project\'s first section when blank.',
    },
    {
      name: 'Order',
      detail:
        '0-based position within the section. Edit to reorder; the next sync reflects the new order in OmniTask.',
    },
    {
      name: 'Status',
      detail:
        'One of "todo", "in-progress", or "done". Also accepts "completed" / "wip" / "doing".',
    },
    { name: 'Priority', detail: 'One of "low", "medium", or "high". Defaults to "low".' },
    { name: 'Due Date', detail: 'Any parseable date (ISO 8601 recommended, e.g. 2026-05-01).' },
    { name: 'Assignees', detail: 'Comma-separated display names.' },
    { name: 'Tags', detail: 'Comma-separated tag names.' },
    { name: 'Description', detail: 'Free text. Multi-line content is preserved.' },
    {
      name: 'ID',
      detail:
        'Auto-generated by OmniTask. Leave blank for new rows — the next sync fills it in.',
    },
    {
      name: 'Updated At',
      detail: 'Timestamp maintained by OmniTask on each sync.',
    },
  ];

  availableTabs = computed<SheetTab[]>(() => this.sheetMetadata()?.sheets ?? []);

  ngOnInit() {
    const p = this.project();
    if (p.googleSheetId && this.isAuthenticated()) {
      this.loadSheetMetadata(p.googleSheetId);
    }
  }

  private async loadSheetMetadata(spreadsheetId: string) {
    this.loadingMetadata.set(true);
    try {
      const meta = await firstValueFrom(this.sheetsService.getSpreadsheet(spreadsheetId));
      this.sheetMetadata.set(meta);
    } catch (err) {
      console.error('Failed to load spreadsheet metadata:', err);
      this.sheetMetadata.set(null);
    } finally {
      this.loadingMetadata.set(false);
    }
  }

  async linkSheet() {
    const raw = this.sheetUrlInput().trim();
    if (!raw) {
      await this.dialogService.alert(
        'Paste a Google Sheets URL or spreadsheet ID.',
        'Sheet Required',
      );
      return;
    }
    const sheetId = this.sheetsService.extractSpreadsheetId(raw);
    this.linking.set(true);
    try {
      const meta = await firstValueFrom(this.sheetsService.getSpreadsheet(sheetId));
      const tabName = meta.sheets?.[0]?.title ?? DEFAULT_SHEET_TAB_NAME;
      await this.projectService.updateProject(this.project().id, {
        googleSheetId: meta.spreadsheetId,
        googleSheetName: meta.title,
        googleSheetTabName: tabName,
        sheetSyncEnabled: true,
        sheetSyncStatus: 'pending',
      });
      this.sheetMetadata.set(meta);
      this.sheetUrlInput.set('');
      this.projectChanged.emit();
    } catch (err) {
      console.error('Failed to link sheet:', err);
      await this.dialogService.alert(
        'Could not open that spreadsheet. Make sure the URL is correct and that you have access.',
        'Link Failed',
      );
    } finally {
      this.linking.set(false);
    }
  }

  /**
   * Toggle the "Create new sheet" form, seeding defaults from the current
   * project name on first open so the user sees a sensible starting value.
   */
  toggleCreateForm() {
    const opening = !this.showCreateForm();
    this.showCreateForm.set(opening);
    if (opening) {
      if (!this.newSheetTitle().trim()) {
        this.newSheetTitle.set(`${this.project().name} — OmniTask`);
      }
      if (!this.newTabName().trim()) {
        this.newTabName.set(DEFAULT_SHEET_TAB_NAME);
      }
    }
  }

  async createNewSheet() {
    const title = this.newSheetTitle().trim();
    const tabName = this.newTabName().trim() || DEFAULT_SHEET_TAB_NAME;
    if (!title) {
      await this.dialogService.alert(
        'Please enter a name for the new spreadsheet.',
        'Title Required',
      );
      return;
    }
    this.creating.set(true);
    try {
      const result = await this.sheetsSyncService.createSheetForProject(
        this.project().id,
        this.project().name,
        { title, tabName },
      );
      const meta = await firstValueFrom(
        this.sheetsService.getSpreadsheet(result.spreadsheetId),
      );
      this.sheetMetadata.set(meta);
      this.showCreateForm.set(false);
      this.projectChanged.emit();
      this.lastSyncResult.set({
        success: true,
        message: `Created "${meta.title}" in Google Sheets and linked it to this project.`,
      });
      setTimeout(() => this.lastSyncResult.set(null), 5000);
    } catch (err) {
      console.error('Failed to create sheet:', err);
      await this.dialogService.alert(
        'Failed to create a new Google Sheet. Please try again.',
        'Create Failed',
      );
    } finally {
      this.creating.set(false);
    }
  }

  async selectTab(tabName: string) {
    try {
      await this.projectService.updateProject(this.project().id, {
        googleSheetTabName: tabName,
        sheetSyncStatus: 'pending',
      });
      this.projectChanged.emit();
    } catch (err) {
      console.error('Failed to select tab:', err);
    }
  }

  async pushAllToSheet() {
    const p = this.project();
    if (!p.googleSheetId) return;
    const tab = p.googleSheetTabName || DEFAULT_SHEET_TAB_NAME;
    const confirmed = await this.dialogService.confirm(
      `This will overwrite all rows in "${tab}" with OmniTask's current tasks. Continue?`,
      'Overwrite Sheet?',
    );
    if (!confirmed) return;

    this.pushing.set(true);
    try {
      await this.projectService.updateProject(p.id, { sheetSyncStatus: 'pending' });
      const result = await this.sheetsSyncService.pushProjectToSheet(p.id, p.googleSheetId, tab);
      await this.projectService.updateProject(p.id, {
        sheetSyncStatus: 'synced',
        lastSheetSyncAt: new Date(),
      });
      this.projectChanged.emit();
      this.lastSyncResult.set({
        success: true,
        message: `✓ Exported ${result.pushed} task${result.pushed === 1 ? '' : 's'} to Google Sheets.`,
      });
      setTimeout(() => this.lastSyncResult.set(null), 5000);
    } catch (err) {
      console.error('Push failed:', err);
      await this.projectService.updateProject(p.id, { sheetSyncStatus: 'error' });
      this.lastSyncResult.set({
        success: false,
        message: 'Export to Google Sheets failed. Check sheet permissions and try again.',
      });
    } finally {
      this.pushing.set(false);
    }
  }

  /**
   * Force an immediate sync, bypassing the auto-sync debounce. The project
   * already auto-syncs on mount and on a 60s interval, so this is effectively
   * a "refresh" affordance for users who want confirmation right now.
   */
  async triggerSync() {
    const p = this.project();
    if (!p.googleSheetId) {
      await this.dialogService.alert('Please link a Google Sheet first.', 'Sheet Required');
      return;
    }
    this.syncing.set(true);
    try {
      const result = await this.autoSync.syncNow(p.id);
      this.projectChanged.emit();
      if (result) {
        this.lastSyncResult.set({
          success: true,
          message: `✓ ${result.added} added, ${result.updated} updated, ${result.pushed} pushed to sheet`,
        });
      } else {
        this.lastSyncResult.set({
          success: true,
          message: '✓ Already up to date.',
        });
      }
      setTimeout(() => this.lastSyncResult.set(null), 5000);
    } catch (err) {
      console.error('Sheet sync failed:', err);
      this.lastSyncResult.set({
        success: false,
        message: 'Sync failed. Please check your connection and sheet permissions.',
      });
    } finally {
      this.syncing.set(false);
    }
  }

  async disconnectSheet() {
    const confirmed = await this.dialogService.confirm(
      'This will unlink the Google Sheet from this project. The sheet itself is not deleted, and your tasks remain in OmniTask.',
      'Disconnect Sheet?',
    );
    if (!confirmed) return;
    try {
      // Use Firestore's deleteField() sentinel to actually remove the fields.
      // The cast is required because deleteField() returns a FieldValue that
      // isn't assignable to the typed string fields on Partial<Project>.
      const disconnectPayload = {
        googleSheetId: deleteField(),
        googleSheetName: deleteField(),
        googleSheetTabName: deleteField(),
        sheetSyncEnabled: false,
        sheetSyncStatus: deleteField(),
      } as unknown as Partial<Project>;
      await this.projectService.updateProject(this.project().id, disconnectPayload);
      this.sheetMetadata.set(null);
      this.projectChanged.emit();
    } catch (err) {
      console.error('Failed to disconnect sheet:', err);
    }
  }

  async reconnectGoogle() {
    // Re-sign in picks up the Sheets scope.
    await this.authService.logout();
  }

  formatSyncDate(date: Date | { toDate: () => Date } | null | undefined): string {
    if (!date) return 'Never';
    const d =
      date instanceof Date ? date : ((date as { toDate?: () => Date }).toDate?.() ?? new Date());
    return d.toLocaleString();
  }

  sheetLink = computed(() => this.sheetMetadata()?.spreadsheetUrl ?? null);
}
