import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'app.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Firebase.initializeApp() will be added in Phase 1 alongside firebase_options.dart
  // (generated by `flutterfire configure`).
  runApp(const ProviderScope(child: OmniTaskApp()));
}
